language: minimal
dist: xenial
before_install:
  - sudo apt-get update && sudo apt-get -y install unzip
  - wget https://downloads.tuxfamily.org/godotengine/3.1/mono/Godot_v3.1-stable_mono_x11_64.zip
  - unzip Godot_v3.1-stable_mono_x11_64.zip -d ${HOME}/godot
  - export GODOT=${HOME}/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64
  - echo $GODOT
script:
  - mkdir ${HOME}/github-builds
  - mkdir ${HOME}/github-builds/linux
  - mkdir ${HOME}/github-builds/windows
  - $GODOT --path ${TRAVIS_BUILD_DIR} --export "Linux/X11" ${HOME}/github-builds/linux
  - $GODOT --path ${TRAVIS_BUILD_DIR} --export "Windows Desktop" ${HOME}/github-builds/windows
  - cd ${HOME}/github-builds/linux
  - ls
  - cd ${HOME}/github-builds/windows
  - ls