language: minimal
dist: bionic
sudo: yes
services:
  - docker
cache:
  directories:
  - docker_images
before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
before_install:
  - docker load -i docker_images/images.tar || true
  - mkdir -p ${HOME}/github-builds/linux
  - mkdir -p ${HOME}/github-builds/windows
  - docker run --rm -it -v ${TRAVIS_BUILD_DIR}/:/app mono:6.6 /bin/bash -c "cd /app/; mono ./.paket/paket.exe restore"
script:
  - docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/app -v ${HOME}/github-builds/windows/:/output gerx03/godot-mono-headless:3.2-beta4 --path /app --export "Windows Desktop" /output/app.exe
  - docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/app -v ${HOME}/github-builds/windows/:/output gerx03/godot-mono-headless:3.2-beta4 --path /app --export "Linux/X11" /output/app
  - ls ${HOME}/github-builds/linux
  - ls ${HOME}/github-builds/windows